import '@/styles/globals.css'
import Head from "next/head";

import { Navbar, Footer } from '@/components'
export default function App({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>VouchDAO V-2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </div>
  )
}
